# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# install:
#     - pip install -U platformio
#
# script:
#     - platformio run


#
# Template #2: The project is intended to by used as a library with examples
#

language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=main.cpp PLATFORMIO_BUILD_FLAGS="-Ddisplay=DISPLAY_SERIAL"
    - PLATFORMIO_CI_SRC=main.cpp PLATFORMIO_BUILD_FLAGS="-Ddisplay=DISPLAY_SSD1306"
    - PLATFORMIO_CI_SRC=main.cpp PLATFORMIO_BUILD_FLAGS="-Ddisplay=DISPLAY_U8G2"

install:
    - pip install -U platformio
    - platformio lib install https://github.com/marvinroger/homie-esp8266.git#v2.0.0-beta.1
    - platformio lib install https://github.com/bblanchon/ArduinoJson.git#v5.10.1
    - platformio lib install ESP8266_SSD1306
    - platformio lib install U8G2
    - platformio lib install SPI

script:
    - platformio ci --lib="." --board=esp12e
